spring:
  mail:
    host: smtp.gmail.com
    username: [Your e-mail]
    password: [Application password]
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true