spring:
  mail:
    host: smtp.gmail.com
    username: projectsbygithub@gmail.com
    password: ffyvmtvqezavwzqo
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true