CREATE DATABASE mininetservicedb;

--Then excute all the things of below
CREATE TABLE IF NOT EXISTS USER_TABLE
(
	USER_ID SERIAL,
	EMAIL VARCHAR(100) NOT NULL,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(500) NOT NULL,
	CREATED_AT VARCHAR(80) NOT NULL,
	UPDATED_AT VARCHAR(80) NOT NULL,
	USER_ROLE VARCHAR(30)
);

INSERT INTO USER_TABLE (EMAIL, USERNAME, PASSWORD, CREATED_AT, UPDATED_AT, USER_ROLE)
VALUES ('pine@gmail.com','PineberryCode','$2a$10$NG2b0hQg/C4.fO3yxXVMIODhOVRLk12yYU3dr9dgWnX6L6oRDV8yS','10-10-2023','10-10-2023', 'ADMIN');